### ISSUE TITLE
pre font sizes don't change font size

### ISSUE THREAD

**Issue by Crell** [platformsh/slides-template#4]
But they do cause the whole code sample block to shift downwards.  Weird.

**Comment by dudenhofer** [comment]
You need to target the `code` within the `pre` since that font size overrides the pre font size. try using `.reveal pre > code` to adjust sizes.

**Comment by Crell** [comment]
Confirmed, that fixes it!

Which do you recommend: `.reveal pre.font--20 > code`, or `.reveal pre > code.font--20`?

**Comment by dudenhofer** [comment]
I'd probably lean toward adding the class to the code so maybe in the future it will be easier to target (and that is the actual element that affects the size).

**Comment by Crell** [comment]
Fixed in master of the psr14 slides.
