### ISSUE TITLE
Blockquote "quote" mark is inconsistently aligned

### ISSUE THREAD

**Issue by Crell** [platformsh/slides-template#6]
Ideally it would be just to the left of the actual content, but my CSS-ful is not good enough to pull that off.

Alternatively we could just remove it, or do something else entirely.  I was just trying to replicate what's in the Google slides, although I don't actually like that effect. :-)  Putting the quote mark behind the text results in the text being harder to read.

(Plus the pink on blue is not a good color combination.)

**Comment by dudenhofer** [comment]
I added a class to do this, it sets the blockquote to `inline-block` so it isn't full-width. But this also required an update to the wrapper class (I added a quote class to the aside). Let me know if you have any issues with this update, I pushed it to the PR.

**Comment by Crell** [comment]
That works for me, although the quote class should probably be scoped to aside elements.

That said, blockquotes look almost exactly like normal text now.  Is there another way to set them off?  My previous template used dotted lines above and below and a color change, but I was never wild about that.
